### ISSUE TITLE
Encrypted Media error when in WorkerGlobalScope shouldn't be TypeError

### ISSUE THREAD

**Issue by mounirlamouri** [WICG/media-capabilities#106]
`TypeError` suggests that the input is incorrect but here, it will just not be possible to make the call. I suggest to switch to `InvalidStateError` though, I'm happy to pick anything else.

**Comment by mounirlamouri** [comment]
Note that I'm writing the implementation in Blink with `InvalidStateError` but we are not shipping quite yet so nothing set in stone.

**Comment by chcunningham** [comment]
> it will just not be possible to make the call

I'm confused - why wouldn't the app developer know when they're in a worker?

**Comment by mounirlamouri** [comment]
My point is that because we only fail in worker for Encrypted Media with the same error type as the one that we use for invalid input, any code that's generic enough my just suppose the input is invalid. Having a completely different error type will allow generic code to differentiate invalid input from running in the wrong context. Surely, they could simply check if they are running in a worker before making the call :)

**Comment by chcunningham** [comment]
Ah, good point. InvalidStateError sounds fine to me. I'll send a PR
