### ISSUE TITLE
Video width and height need to be more precisely specified

### ISSUE THREAD

**Issue by mwatson2** [WICG/media-capabilities#11]
There are a variety of definitions for the width and height of a video:
- The number of horizontal and vertical encoded pixels in the encoded video pictures
- The number of visible horizontal and vertical encoded pixels in the encoded video pictures
- The number of horizontal and vertical screen pixels to which the video is rendered

These differ based on pixel aspect ratio, video aperture, picture aspect ratio vs rendering area aspect ratio and scaling.

I think the second bullet above may be most relevant for capability discovery, but it deserves discussion.

**Comment by PauKerr** [comment]
I would suggest we choose the second or third option above as I believe what the application will care about is what is visible. In the idea it would be what is rendered but that may not be discoverable by the user agent and thus option 2 would be the fallback.

**Comment by chcunningham** [comment]
I think discussion here sums it up nicely. Lets take option 2.

**Comment by mounirlamouri** [comment]
Happy with option 2, will do the change later.

**Comment by jdsmith3000** [comment]
Does this mean that horizontal and vertical resolution would report the pixel sizes of the current window on the display?  So if videos start small, the capabilities query would bias the app toward lower resolution content.  And should the window size be changed (e.g. maximized), the app would be notified, repeat the query and take advantage?  This is the behavior that makes most sense to me, if that's the case.

**Comment by chcunningham** [comment]
We're talking about the pixels in the encoded pictures, irrespective of window size.

There are separate [existing APIs](https://www.w3schools.com/jsref/event_onresize.asp) for to query window size and monitor for resizing. I think many apps will use those as a starting point for deciding on an ideal resolution and then query media capabilities to see such a resolution can be smoothly decoded. If they detect a resize (e.g. size increase) via these separate APIs they can query MediaCapabilities to see if higher resolutions are well supported.

**Comment by jdsmith3000** [comment]
Okay.  Makes sense to have Video Configuration with and height apply to the content (i.e. option 2) and the Screen API width and height apply to the physical device/viewport.  My question had a bit to do really with the screen spec, but coupled with a notification of viewport changes, this seems workable.
