### ISSUE TITLE
Add detection of alpha channel support

### ISSUE THREAD

**Issue by jernoble** [WICG/media-capabilities#112]
Browsers have inconsistent support for rendering alpha channels in media which contains such.

* Chrome and Firefox support alpha channel rendering in WebM bearing VP8. [[1](https://developers.google.com/web/updates/2013/07/Alpha-transparency-in-Chrome-video)]
* Edge supports WebM+VP8 but not alpha channel rendering.

In addition to WebM/VP8 & VP9, the HEVC spec allows for an alpha channel layer, though no UA currently supports it.

This support is currently not feature detectable. Workarounds include rendering a data-url backed video to canvas and reading back pixels as well as a straight up UA check [[2](https://stackoverflow.com/questions/29416579/how-to-feature-detect-if-browser-supports-webm-alpha-transparency)].

Previous objections to adding a parameter to query alpha channel support to Media Capabilities include:

* Alpha channels are part of the codec specification; UAs which don't support (e.g.) WebM/VP8 with alpha are out of compliance with the specification and should not advertise support for VP8 through Media Capabilities.

[[3](https://developers.google.com/web/updates/2013/07/Alpha-transparency-in-Chrome-video#how_did_they_do_it)] states that the VP8 bitstream did not support alpha transparency layers, and adding support was done in a backwards compatible way so as not to break existing players. Similarly, alpha channel layers in HEVC are treated as "optional auxiliary information" and support is not required for a conforming player.

* Support should be signaled somewhere else, like the MIME Type string.

There is no way of signaling alpha layer support in the "codecs" parameter of the MIME type, and every API which takes a MIME type to ask support (such as Media Capabilities, HTMLMediaElement.canPlayType(), MediaSource.isTypeSupported()) all either explicitly reject or ignore non-"codecs" parameters to the ContentType.

**Comment by cconcolato** [comment]
I support this proposal.

Support for alpha is not necessarily part of the codec. For example, you may use stream A for the RBG/YUV part and stream B for the alpha channel. For example, even if support for monochrome encoding is part of the basic AV1 support, it does not mean the combination of an AV1 RGB stream with an AV1 monochrome stream is supported. 

In fact, the ISOBMFF/MIAF ecosystem defines how to combine them at the system layer, in a codec agnostic way. For example, they define the notion of 'auxiliary video track', how to signal the exact type of auxiliary track (e.g. alpha). MIAF even requires support for parsing auxiliary tracks and rendering alpha tracks:
> MIAF readers shall support all auxiliary images and be capable of outputting any auxiliary images
associated with the output image(s) with their type (notably depth-map and alpha-plane auxiliary images). MIAF renderers shall interpret alpha planes and should support alpha blending using alpha-plane auxiliary
images.

assuming the following constraints:
> When alpha planes are used, the constraints specified in 7.3.5.2 apply; and for every sample of the master
image sequence or video track, there shall be a sample of the alpha plane track with the same composition
time. The width and height of the decoded alpha plane pictures shall be the same as the width and height of the pictures of the associated video track, respectively.

MIAF even defines the brand `MiAC` as follows:
> This application brand is intended to be used for MIAF video files that are CMAF compatible and
contain an alpha plane sequence associated with the video track.

Maybe the detection mechanism could be based on that.

**Comment by jernoble** [comment]
W.R.T. MIAF, we’ve gone back and forth with signaling profiles and brands through the MIME type, and always ran aground on the rocky shoals of “codec parameters only”, and that’s part of the reason for the DisplayCapabilities part of the spec, rather than just adding “profile=hdr10+” to the MIME type.  That said, it’s good to know that this is addressed in MIAF. 

I’ll note that the MIAF language you quoted says that implementations SHALL recognize but only SHOULD render.  Which means even if we had a “profile=maif” MIME type parameter, we’d still need a mechanism for querying alpha channel support to distinguish SHOULD from DOESN’T.

**Comment by jernoble** [comment]
All that said, @cconcolato, could you clarify something for me? You said:

> [T]he ISOBMFF/MIAF ecosystem defines how to combine them at the system layer, in a codec agnostic way. For example, they define the notion of 'auxiliary video track', how to signal the exact type of auxiliary track (e.g. alpha). 

Does the "codec agnostic way" imply that alpha channel "auxiliary video tracks" can be of a different codec type than the main track?  If so, that would complicate the API design of a alpha channel detection query.

**Comment by cconcolato** [comment]
What I meant was that ISOBMFF/MIAF is not limited to MPEG codecs, and for example, you can use it for AV1. However, you're right that the boxes and other signaling tools allow you to associate an RBG video encoded with codec X with an alpha video encoded with codec Y. This could be interesting in general but gets tricky in practice. MIAF restricts that a bit:
> Thumbnail or auxiliary sequences shall conform either to the requirements the same MIAF codec profile as
the MIAF image sequence or video to which it is linked, or to the requirements of a format defined in clause
9.

The problem is the mention of "clause 9" which defines JPEG in MIAF. I think this MIAF sentence is there to mimic the case of auxiliary images, where adding JPEG support makes sense and does not add cost. For video, I'm not sure it makes sense, as I don't know any player capable of playing a ISOBMFF-packaged JPEG video sequence.

**Comment by jernoble** [comment]
@cconcolato Thanks for the clarification. It would be tempting to solve this issue by passing multiple "codec" parameters in contentType:, but there's already language in Media Capabilities proscribing that:

> In the context of this specification, a MIME type is also called content type. A valid media MIME type is a string that is a valid MIME type per [mimesniff]. If the MIME type does not imply a codec, the string MUST also have one and only one parameter that is named codecs with a value describing a single media codec. Otherwise, it MUST contain no parameters.

The ability to have different codecs for different layers in ISOBMFF seems theoretical, and that ability is already restricted in MIAF, so perhaps ignoring this corner case for now would be prudent in order to solve the more practical use case of the same codec for RGB and alpha.

**Comment by chcunningham** [comment]
Generally I think the proposal to add alpha makes sense. I want to check with Vignesh (who implemented VP8 alpha in chrome) to get his take. IIUC, alpha support for VP8 in WebM didn't require a totally separate stream like @cconcolato mentions for MIAF. Maybe its fine to have a single "alpha" attribute in the query that means "separate alpha stream" in the context of MIAF while meaning something very different for a webm vp8 query. Maybe :)

**Comment by jernoble** [comment]
👍🏻
I was going to propose "hasAlpha" as a VideoConfiguration parameter–taking a boolean–as a slightly less ambiguous name than simply "alpha".

**Comment by mounirlamouri** [comment]
Does that mean that the UA should assume that there is no alpha channel unless `alpha`/`hasAlpha` is specified?

**Comment by jernoble** [comment]
For codecs or containers where alpha channel support is optional (and I can't off the top of my head come up with an example where alpha channel support is mandatory), I would presume that the absence of `hasAlpha` would imply no alpha channel was present.

**Comment by chcunningham** [comment]
> I want to check with Vignesh (who implemented VP8 alpha in chrome) to get his take. IIUC, alpha support for VP8 in WebM didn't require a totally separate stream like @cconcolato mentions for MIAF. Maybe its fine to have a single "alpha" attribute in the query that means "separate alpha stream" in the context of MIAF while meaning something very different for a webm vp8 query. Maybe :)

Vignesh wrote back that the VP8 implementation was actually pretty similar to whats described for ISOBMFF/MIAF. Not an entirely separate track, but it relies on attaching alpha data to each frame at the container level (WebM BlockAdditional). He feels the two methods are close enough that "hasAlpha" works well. 


>  I would presume that the absence of hasAlpha would imply no alpha channel was present.

Sounds good to me. @jernoble, want to send a PR our way?
