### ISSUE TITLE
Please add support for video Transfer Function

### ISSUE THREAD

**Issue by mwatson2** [WICG/media-capabilities#13]
The `codecs` component of MIME content strings does not include information about the transfer function (for example, gamma, PQ, HLG) that was used to encode the video (since this information is not used by the video codec itself).

We would like to be able to query support for these different transfer functions in association with the codec.

**Comment by johnpallett** [comment]
I added a list of eotf types to #10

**Comment by mwatson2** [comment]
Dup of #10.
