### ISSUE TITLE
Color gamut and bit depth support may different for graphics and video

### ISSUE THREAD

**Issue by mwatson2** [WICG/media-capabilities#15]
Related to #14.

Devices exist which support Wide Color Gamut and high bit depth for video rendering but not for graphics. It should be possible to discover that this video support exists without implying that graphics support also exists.

**Comment by ddorwin** [comment]
Separate from media capabilities, there may be color correction details (or implementation requirements) that are important in such cases.

A related issue is that such devices may use different resolutions for video and graphics. Thus, the `screen` dimensions may not be a good indicator of the video rendering capabilities.

**Comment by mounirlamouri** [comment]
I've open #25 for the generic graphics vs video issue. I don't think we should attempt to solve this for v1.
