### ISSUE TITLE
Screen width/height issues

### ISSUE THREAD

**Issue by halliwell-g** [WICG/media-capabilities#17]
Currently it's not possible for a page to detect the display's resolution capability for video display.  A few things to note:
* decode height/width capability can be independent of screen height/width.
* window.screen/width is defined in css pixels, not physical pixels.
* additionally, some hardware displays video in separate plane which may have different resolution than graphics.

**Comment by ddorwin** [comment]
For the third item, see also #15.

**Comment by jpiesing** [comment]
21:9 TV sets come and go. When Philips last did 21:9 sets, the video would fill the entire 21:9 area of the display but graphics was in a separate plane which was the centre 16:9 of the 21:9.

**Comment by mounirlamouri** [comment]
It sounds to me that this is a duplicate of #25. Please, reopen if I misunderstood.
