### ISSUE TITLE
Change video bitrate format to kbps?

### ISSUE THREAD

**Issue by beaufortfrancois** [WICG/media-capabilities#19]
It looks like it is more common to refer to video bitrate in kbps than bps.

Hence I suggest something like:

> The bitrate member represents the number of average bitrate of the video track. The bitrate is the number of thousand bits per second used to encode a second of the video track.

**Comment by mounirlamouri** [comment]
The reason this is in `bps` is because it can be a `long` and we don't need to worry about floating points. It's also matching the DASH MPD `bandwidth` field which might be useful. Will keep this open but unless there are other similar feedback, I'm inclined to keep `bps`.

**Comment by beaufortfrancois** [comment]
I've noticed HLS also use `bps` for the `bandwidth` field.
Let's close this and keep `bps`.
