### ISSUE TITLE
"MediaSource" as an enum value is unusual

### ISSUE THREAD

**Issue by foolip** [WICG/media-capabilities#20]
https://wicg.github.io/media-capabilities/#mediaconfigurationtype

https://w3ctag.github.io/design-principles/#casing-rules suggests "lowercase, dash-delimited" for enum values, although certainly exceptions can be found.

**Comment by mounirlamouri** [comment]
I have a commit changing this to `media-source`. It follows the spec shortname so it's probably as good as anything else.

**Comment by foolip** [comment]
SGTM if https://github.com/WICG/media-capabilities/issues/3 doesn't make the enum go away.
