### ISSUE TITLE
What are the mime types of audio and video tracks?

### ISSUE THREAD

**Issue by foolip** [WICG/media-capabilities#23]
https://wicg.github.io/media-capabilities/#dom-audioconfiguration-type
https://wicg.github.io/media-capabilities/#dom-videoconfiguration-type

This says "The `type` member represents the MIME type of the audio/video track."

Does for example VP8 have a MIME type of its own? "video/webm;codecs=vp8" includes the container, and "video/vp8" doesn't seem to exist.

**Comment by foolip** [comment]
Hmm, perhaps "A valid VideoConfiguration type MUST include a media type, subtype and full codecs description" is the answer, namely that the container must always be included, even for something like audio/opus that does have a container-less MIME type?

**Comment by mounirlamouri** [comment]
/CC @chcunningham as it matches a few comments from #32 

@foolip shouldn't opus be `audio/ogg; codecs=opus`?

I'm going to attempt a better description of the mime type requirements and will CC both of you there.

**Comment by chcunningham** [comment]
I've always thought of the mime types (or perhaps content types - not sure which is preferred name) as matching those we pass into HTMLMediaElement.canPlayType. These generally specify a mix of container and codecs, except in cases where the container is really just a packet stream (e.g. "audio/aac", "audio/flac", "audio/mp3"). I hadn't planned on allowing things like "video/vp8" -- it seems too ambiguous to decide whether we can support this without explicit mention of its container.

**Comment by foolip** [comment]
> @foolip shouldn't opus be audio/ogg; codecs=opus?

I'm not sure, audio/opus (https://tools.ietf.org/html/rfc7587) seems to be for Opus over RTP, but the opusenc tool suggests using a .opus file ending, even though it is an Ogg container. It could be that both `audio/ogg; codecs=opus` and `audio/opus` can be used to describe that, but I'd check with @jmvalin about that.

**Comment by mounirlamouri** [comment]
If both `audio/ogg; codecs=opus` and `audio/opus` are technically allowed, I think we could simply required the version with the `codecs` parameter for this API.

**Comment by foolip** [comment]
Looks like in Chrome, `audio.canPlayType('audio/opus')` returns the empty string but `audio.canPlayType("audio/ogg;codecs=opus")` returns "probably" so that would certainly be consistent.

**Comment by chcunningham** [comment]
I'm happy to just allow the version with codecs=. But also, I think foolip's other comment [here](https://github.com/WICG/media-capabilities/pull/35/files/c58c19d20cf1c00694215c857abc0d4cf66b51b0#diff-ec9cfa5f3f35ec1f84feb2e59686c34d) may resolve this nicely.

> Should there not be some other step in some other part of the spec that checks if the content type is supported (not just syntactically valid) which could make these checks unnecessary?

Taking that approach, chrome would today allow the codecs= version and reject the other.
