### ISSUE TITLE
Rename `bitrate` to `bandwidth`

### ISSUE THREAD

**Issue by beaufortfrancois** [WICG/media-capabilities#27]
For consistency, I was wondering if we should rename the `bitrate` field to `bandwidth` as it is the word used in HLS and DASH to refer to the bitrate in metric multiples of bits per second.

**Comment by mounirlamouri** [comment]
You have a good point. Even though I find the word `bandwidth` slightly confusing in this context, it's probably better for consistency.

**Comment by mwatson2** [comment]
I think what DASH and HLS refer to as bandwidth is *not* the same as what we are referring to as bitrate here.

*bandwidth* is a measure of available resource on a channel. At least in DASH, last I looked, it specified the constant bandwidth required to stream the representation within some latency bound.

*bitrate* is a better term for what we need here, which is a direct measure of the encoded bitrate of the video stream.

So I think we should leave it as bitrate.

**Comment by mwatson2** [comment]
@mounirlamouri I explained above why what we havebhere is different from DASH. Using the same term for somethIng very different will cause more confusion not less.

Could you either answer my point or revert the change please ?

**Comment by mwatson2** [comment]
This issue should be reopened, but I don't seem to be able to do that from the mobile interface.

**Comment by mounirlamouri** [comment]
@mwatson2 sorry for merging this change after your comment: there was a race condition :)

Happy to revert the change but I just want to clarify something: I expect developers to use exactly the same value for `bandwidth` and `bitrate`. Do you expect developers to sometimes provide a `bandwidth` to DASH/HLS that would be different from the `bitrate` sent to this API? in which cases?

**Comment by PauKerr** [comment]
The bandwidth attribute found in the DASH specification is used to model the data channel that delivers the media. It is combined with the minBufferTime attribute to determine how much data must be buffered before playback to allow for continuous playback on a _hypothetical_ channel with a constant bandwidth represented by the attribute. As such, it is different from the average bit rate of the media: it is used to represent an attribute of the delivery channel not the platform capability.

**Comment by mounirlamouri** [comment]
I've renamed the property to `bitrate`.
