### ISSUE TITLE
Consider adding a new `MediaConfigurationType` for Real-Time v/a recording

### ISSUE THREAD

**Issue by miguelao** [WICG/media-capabilities#28]
Consider adding a new [`MediaConfigurationType`](https://wicg.github.io/media-capabilities/#enumdef-mediaconfigurationtype) to describe real-time recording.

---
How it could be done: This spec is based on the [`query(MediaConfiguration configuration)`](https://wicg.github.io/media-capabilities/#navigators-extensions); [`MediaConfiguration`](https://wicg.github.io/media-capabilities/#mediaconfiguration) has a [`type`](https://wicg.github.io/media-capabilities/#mediaconfigurationtype) with available entries: "file" and "media-source".  We could add a e.g. `media-recording` entry, which would make things look a bit like e.g.:

```
navigator.mediaCapabilities.query({
  type : "media-recording",
  video : {contentType : "video/webm", width : 1280, height : 720}
});
```
 ... returning (a Promise resolved with) an interface [`MediaDecodingAbility`](https://wicg.github.io/media-capabilities/#media-decoding-ability), 
  e.g. `{ supported : true, smooth : false, powerEfficient : true };`

---
This would provide a solution to a controversial debate in medicapture-record (see https://github.com/w3c/mediacapture-record/issues/59 and https://github.com/w3c/mediacapture-record/pull/65); @uysalere, @pehrsons since we discussed it before.

**Comment by miguelao** [comment]
Also @chcunningham and @miu-at-google so they can voice suggestions/concerns.

**Comment by uysalere** [comment]
I believe this would be good solution for the referred bugs. Considering that we might add encode abilities as well in the future, renaming the interface MediaDecodingAbility to something more generic that would cover encode and recording would be useful, i.e. MediaProcessingAbility. The current fields of the interface look sufficient.
