### ISSUE TITLE
Need exceptions for invalid input

### ISSUE THREAD

**Issue by chcunningham** [WICG/media-capabilities#32]
There are a number of ways to provide invalid input to this API. Off the top of my head:

1. empty content type
2. invalid content type
3. negative or NaN values for things like fps, bitrate, etc.

We should consider following other specs (e.g. MediaSource) and throw exceptions to help devs differentiate between missing support vs malformed queries. MediaSource likes to throw TypeError for these - not sure what the current best practice is.

**Comment by chcunningham** [comment]
We should also probably ban mention of multiple codecs in a single configuration type. For example:

'audio/webm; codecs="opus, vorbis"

While we do support those codecs on their own in webm, they are never mixed in a single file and its unclear that this would jive well with the single values for bitrate and samplerate also found in the AudioConfiguration. 

This sort of codec switching is also not currently supported by MSE (you're allowed to append multiple files into a source buffer, but they must have matching codec/mime types). Perhaps in the future this will be supported and we consider revising the API to take in a series of audio/video configurations... but I think thats getting ahead of ourselves for now.

**Comment by mounirlamouri** [comment]
Regarding empty/invalid content type, the spec requires a "valid videoconfiguration" and "valid audioconfiguration" which implies valid content types. However, it's loosely defined and I will have a look at this.

Regarding NaN and negative values for fps/bitrate and such, it needs to be defined indeed.

I agree for the `codecs` and requiring one and no more than one sounds like the right thing to do for now.
