### ISSUE TITLE
HDCP Policy Check: question on usage restrictions

### ISSUE THREAD

**Issue by PauKerr** [WICG/media-capabilities#42]
I believe clarification needs to be provided as to when a call to the proposed getStatusForPolicy method can be used. Is is sufficient to simply create an instance of MediaKeys from a  MediaKeySystemAccess.createMediaKeys() call and then make a call to getStatusForPolicy(). 
Specifically, can getStatusForPolicy() be called and subsequently return a usable value without needing to:
- assign the MediaKeys object to an HtmlMediaElement: without needing to make a setMediaKeys() call?
- call createSession()?

**Comment by cpearce** [comment]
For Firefox at least, the connection to the CDM is established by the time the createMediaKeys() promise is resolved. So, assuming we are going to be asking the CDM to check whether an HDCP policy is supported, for us there would be no technical need to attach the MediaKeys to the HTMLMediaElement for us to be able to query it for support.

**Comment by joeyparrish** [comment]
Yes, it was our intent that no media element would be required, nor any sessions.

**Comment by xhwang-chromium** [comment]
What this API does is to get the key status of a hypothetical key with the given policy. It does not require real  keys so it does not need any real MediaKeySessions. Since this is only key status check, it doesn't require the MediaKeys to be attached to any HTMLMediaElement either.

**Comment by PauKerr** [comment]
Thanks for the clarification. Could this usage model be added to the text? As such, we would find this API extension very useful.

**Comment by xhwang-chromium** [comment]
Paul: Just to clarify, the current doc is just an explainer for early discussion. It is definitely missing a lot of details, e.g. algorithms of the proposed API. But yes, we'll add this usage model to the doc for clarification.

Other than that, do you have any other concerns? Thanks!
