### ISSUE TITLE
hwAccel should be indicated separate from powerEfficient

### ISSUE THREAD

**Issue by jdsmith3000** [WICG/media-capabilities#45]
One subcase (now) for powerEfficient is formats that are hardware accelerated.  We believe this capability should be made into it's own MediaCapabilitiesInfo attribute.  powerEfficient could be retained, so websites could see hw accel and powerEfficient directly.

**Comment by mounirlamouri** [comment]
Not exposing hardware accelerated is intentional because we believe that the information itself isn't enough and usually this is a proxy for performance (visual and battery). Is there a use case for hardware accelerated that we are missing here?

To detail a bit what we mean by this is that for example, a low quality stream (let say 360p) would most likely be power efficient and some platforms might not even trigger the hardware decoder for those. I believe macOS does something like that. Very recently, [Chrome started to do something similar](https://chromium-review.googlesource.com/c/520710/).

**Comment by jdsmith3000** [comment]
We accept that there are instances where software decode is power efficient, but believe that websites will want to know if hwaccel is provided for other cases, notably those involving high resolution content.  Our own experience with WebM/VP9 is that it needs hwaccel in these cases to be similar in power with other hwaccel formats.  Because of this, we currently enable VP9 only when hwaccel is present.  I would like to make this a decision by the client, and believe we need to report hwaccel support for this API to allow that. 

I don't see these attributes as exclusive, and can imagine responding with powerEfficient=true in parallel with hwaccel=false.  Reporting both seems preferred to me so that we provide capability information web clients request.

**Comment by mounirlamouri** [comment]
If I understand correctly, the proposal would be to have `hwaccel` returns the same value as `powerEfficient` unless `powerEfficient` returns `true` in which case it may return `false`. What would be the use case for a website to know that something is power efficient but not hardware accelerated?

**Comment by jdsmith3000** [comment]
I asked because `powerEfficient `isn't explicit, and I think the more important question is whether the format is `hwaccel `or not.

**Comment by btotr** [comment]
```hwaccel``` will also be less ambiguous for a Cloud Browser solution. See one of the use cases by the W3C Cloud Browser TF: https://btotr.github.io/cloud-browser-tf/#application-needs-to-virtual-media-capabilities

**Comment by mrstux** [comment]
It seems short-sighted to gate playback quality based on whether something is hardware accelerated or not. The requirement for hardware acceleration today, may not be true in the future on future devices.

There are only two real questions that matter

1) will it play smoothly
2) will it play in a power efficient manner

Hardware Accelerated doesn't matter for determining if the content should be served, what matters is will it play, or if you care, will it play without running the CPU at high levels and churning through battery.

In the future its quite possible that a video format could be trivially decoded, even without hardware acceleration.

**Comment by chcunningham** [comment]
Agree with those arguing _against_ a new hwAccel attribute and I don't think I could argue it better. Lets consider it dead.
