### ISSUE TITLE
Handle Encrypted Content

### ISSUE THREAD

**Issue by beaufortfrancois** [WICG/media-capabilities#47]
Would it make sense to add CDM to the configuration in `mediaCapabilities.decodingInfo()` for encrypted content  as it would certainly affect smoothness and power efficiency?

**Comment by PauKerr** [comment]
Do you mean CDM as an attribute to signal that a CDM will be used or would you want to indicate a specific CDM?

**Comment by beaufortfrancois** [comment]
Yes.

**Comment by mounirlamouri** [comment]
I've renamed the issue to make it more generic for EME supported as we currently do not support EME in Media Capabilities.

**Comment by jyavenard** [comment]
sounds like a worthwhile addition.. Especially when some EME decoders are software only

**Comment by chcunningham** [comment]
[PR is out](https://github.com/WICG/media-capabilities/pull/101). This follows the approach proposed in the [explainer](https://github.com/WICG/media-capabilities/pull/80) but does not yet add an API for querying support for transitioning between configurations.

**Comment by mounirlamouri** [comment]
#101 resolved this.
