### ISSUE TITLE
MediaKeysPolicy interface in 'HDCP Policy Check' proposal looks useless

### ISSUE THREAD

**Issue by smaug----** [WICG/media-capabilities#49]
Looks like browser are implementing HDCP Policy Check proposal even without a spec!
And I looked at the proposal [1], and just by looking at that MediaKeysPolicy seems to be useless.
Why not just pass a dictionary to getStatusForPolicy?

@xhwang-chromium

[1] https://github.com/WICG/media-capabilities/blob/master/eme-extension-policy-check.md

**Comment by mounirlamouri** [comment]
The rationale behind using an interface over a dictionary (assuming this is the question) is because in the future if new fields are added, a website can feature detect them.

**Comment by smaug----** [comment]
And why you can't do that with dictionaries?

**Comment by mounirlamouri** [comment]
As far as I know, we can't do feature detection on dictionaries but I feel like I'm going to be taught new things :)

**Comment by smaug----** [comment]
The normal way to do feature testing with dictionaries is to have throwing getters.

**Comment by mounirlamouri** [comment]
I wasn't aware of the throwing getter solution. It sounds like a hack to me but if it's the common pattern, happy to switch to a dictionary. + @annevk @domenic to confirm

**Comment by xhwang-chromium** [comment]
To make this discussion complete, can we have an example here to use throwing getter to detect new feature here? It's not obvious to me :)

**Comment by smaug----** [comment]
Using Event interface as an example:
new Event("foo", { get bubbles() { throw "bubbles supported"}});

**Comment by mounirlamouri** [comment]
@xhwang-chromium I've also suggested a change in the Chromium CL to test that the throwing getter is working with the current min HDCP version field.
