### ISSUE TITLE
EME HDCP Policy Check: Please reconsider scope.

### ISSUE THREAD

**Issue by tinskip** [WICG/media-capabilities#55]
The HDCP policy check is currently at the MediaKeySession scope.  This is the wrong scope for the following reasons:

- The application may want to perform the check before a session is created.
- Once the session is available, and a license is acquired the application ought to use the MediaKeyStatusMap to determine which streams can be played.

So, the main use case for this policy check is to check initial conditions.  I  believe MediaKeySystemMediaCapability may be a better place for it, possibly as an "outputProtection" field.

**Comment by xhwang-chromium** [comment]
The API is added on MediaKeys interface, not MediaKeySession interface:

```
partial interface MediaKeys {
  Promise<MediaKeyStatus> getStatusForPolicy(MediaKeysPolicy policy);
}
```
So applications can call it right after MediaKeys creation, without waiting for a MediaKeySession to be created.

**Comment by mounirlamouri** [comment]
Closing because I believe @xhwang-chromium answers the raised concerns.
