### ISSUE TITLE
MediaKeySystemMediaCapability ?

### ISSUE THREAD

**Issue by tinskip** [WICG/media-capabilities#59]
I find the need to compose a JSON message for a single policy field to be excessive, and it might make sense if the contents of this message were DRM system-specific, but they are to be defined in spec instead.  Also, as I mentioned in #55, MediaKeySystemMediaCapability would probably be a better place for this, as it is basically a query mechanism to be invoked early. A single "requiredOutputProtection" field there ought to suffice.

**Comment by xhwang-chromium** [comment]
Could you please clarify the issue a bit more?

1. What JSON message do you mean? Do you mean the actual HDCP version string?
2. By MediaKeySystemMediaCapability, do you mean MediaKeySystemAccess? The problem with that is when MediaKeySystemAccess is called, no CDM instance has been created. We do need a CDM instance to ensure consistency and avoid unnecessary complexity.

**Comment by tinskip** [comment]
1. It looks like I was looking an old version of the spec.
2. I think you are limiting the external API due to an internal implementation detail.

**Comment by mounirlamouri** [comment]
Is there anything still required here or should we close?

**Comment by chcunningham** [comment]
Discussion seems to have stalled. Incubation of HDCP issues has moved to http://github.com/wicg/hdcp-detection - please re-file there if you'd like to continue.
