### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by beaufortfrancois** [WICG/media-capabilities#61]
Media Capabilities draft has has two identical paragraphs for decoding while it should be about decoding AND encoding capabilities:

https://github.com/WICG/media-capabilities/blob/f95c611b7d1fc09498c007c83d6fe3c656a16340/index.bs#L88-L103

**Comment by beaufortfrancois** [comment]
gentle ping @mounirlamouri

**Comment by chcunningham** [comment]
This was fixed
https://github.com/WICG/media-capabilities/commit/728af0351f517bf594c384df41796af843d5f43c#diff-ec9cfa5f3f35ec1f84feb2e59686c34d
