### ISSUE TITLE
API request: define an audio or video configuration by supplying the init segment

### ISSUE THREAD

**Issue by wilaw** [WICG/media-capabilities#67]
Can the video and audio configurations have an optional definition mode in which the corresponding init segment of the media is supplied as a binary object? This will help address deficiencies in codec strings which are insufficient in describing the dynamic range and color volume combinations which may occur in current or future media. These attributes are not captured by the presently defined fields of width, height, bitrate and framerate. 

Examples of such init segments:
- https://dash.akamaized.net/akamai/bbb_30fps/bbb_30fps_480x270_600k/bbb_30fps_480x270_600k_0.m4v 
- http://rdmedia.bbc.co.uk/dash/ondemand/testcard/1/avc3-events/1920x1080i25/IS.mp4
- http://demo.unified-streaming.com/video/ateam/ateam.ism/dash/ateam-video=1996000.dash

Will Law
WAVE Project  - Technical Working Group Chair

**Comment by PauKerr** [comment]
I agree with Will that the VideoConfiguration.contentType is too limiting when trying to determine the color space and dynamic range capabilities of the decoder. At this point, we have browsers that can support 4K HDR video but querying the browser via css, etc, will return only sRGB/SDR capabilities. This can be further complicated by the case where the platform can support the VideoConfiguration in the decoder but not render on an HDR capable display. (see comments https://github.com/WICG/media-capabilities/issues/14 )

I feel that both this issue and #14 can be addressed by allowing more than a codec string as the basic query. The attributes of the decoder and render elements, along with the codec definition represented by the contentType string are necessary to characterize the platform.

Paul Kerr
Netflix

**Comment by chcunningham** [comment]
Hey Will, Paul, apologies for letting this sit so long. We've been let HDR stuff sit on the back burner while we prioritized EME.

I generally agree with more is needed to describe stream color and rendering capabilities, but I'd prefer to see this done by adding fields to the input configuration. Paul suggests something along those lines in Issue #14 - I need to give it more thought. Init segments are really an MSE concept whereas MediaCapabilities isn't MSE specific. Also, sniffing binary blobs is notoriously difficult to get right and is a juicy attack surface for folks wanting to compromise the browser. 

I fully support a JS library that would translate init segments into the API's fields.

**Comment by wilaw** [comment]
@chcunningham  - you make a reasonable point that accepting arbitrary binary objects represents an easy attack surface. I would support Paul's initiative around an expanded field set as an alternate.

Note however that it is important that any information the player is expected to give to the media-capabilities api should be information which it can read directly from the playlist/manifest and simply pass through. Players should never be required to hold updated knowledge about which color profiles are associated with which codec strings for example. 

One convenient interface we could leverage to reduce the cardinality of potential attribute fields that a player would need to query is that of "media profiles". Media Profiles are ready-made and standardized bundles of properties/capabilities. So instead of saying do you support "AVC High level 4.0 with BT 709 OETF and AVC1.6400028", the player could simply ask do you support "cfhd". CMAF represents the converged future of HLS and DASH file containers and media profiles have been standardized by MPEG and WAVE. It would be elegant and concise if we could query capabilities using the normative cmaf brands as shown in the tables below. 

![screen shot 2018-06-14 at 8 47 36 pm](https://user-images.githubusercontent.com/2762250/41449186-6ad7b6c0-7014-11e8-846d-2cfbddf4d935.png)


![screen shot 2018-06-14 at 8 47 45 pm](https://user-images.githubusercontent.com/2762250/41449197-7610e4c6-7014-11e8-9d0b-9f97fcd9fe1a.png)

**Comment by chcunningham** [comment]
Apologies for the slow reply. I definitely follow the ease-of-use arguement for profiles=. 

This is similar to how the multipart vp09 string is working already. If we expand the the field set for color and other properties, the values of those fields can be inferred from the  parsed vp9 string. 

I do have some concerns about profiles though. 

1. Everytime a new profile is minted UAs will need to update their parsing code. As-is MC allows callers can supply any combination of values. This puts more burden on callers, but it affords them more flexibility and means deploying a new combination isn't blocked on UA releases. 

2. Profiles constrain to a handful of colors and eotfs, but a handful is still ambiguous. With MC we aim to give confident answers (no more "maybe"), which motivates disallowing ambiguous inputs. We intentionally don't have a way to say we support _some_ of the things in your profile. Perhaps an all-or-nothing approach could work, but it seems a bit fragile. The people that make devices and those that define profiles may not read my github posts ;). 

Aside: for existing media APIs, it seems like additional prameters are by default ignored. For instance, the following returns "probably" in all edge, ff, and chrome.

document.createElement('video').canPlayType('video/mp4; codecs="avc1.42E01E"; profiles="foo"')

Not so much a problem for the shiny new MC api, but backward compat with other APIs is going be tricky.

**Comment by chcunningham** [comment]
conversation about profiles moving to #98
