### ISSUE TITLE
Where do we represent MIME media type parameters?

### ISSUE THREAD

**Issue by alvestrand** [WICG/media-capabilities#68]
I read through this spec quickly today, and found:

"A valid media MIME type is a string that is a valid MIME type per [mimesniff]. If the MIME type does not imply a codec, the string MUST also have one and only one parameter that is named codecs with a value describing a single media codec. Otherwise, it MUST contain no parameters."

Some codecs (most particularly H.264) have a long established MIME type with a ton of parameters, many of which (such as profile-id) are critical for distinguishing versions of the codec with different capabilities. In SDP, those are represented in the "fmtp" parameter.

Where is one supposed to put these in a VideoConfiguration construct?

**Comment by alvestrand** [comment]
Tagging @fluffy and @aboba for more informed opinions.

**Comment by chcunningham** [comment]
I'm not familiar with how profiles are described in SDP, but an example of an H264 (in MP4) contentType would be:

video/mp4; codecs="avc1.64001f"

The avc1.* bit describes h264 using the "high" profile. This format is defined in rfc6381. The values following the '.' (rfc: avcoti) break into bytes describing the profile_idc, constraint_set flags, and level_idc. 

My preferred tool to get the mime for mp4 files is to use MP4Box.js and check the "MIME" in the file-overview tab
http://download.tsi.telecom-paristech.fr/gpac/mp4box.js/filereader.html

Please let me know if some aspect of H264 profiles is covered in SDP, but not by the above.

**Comment by chcunningham** [comment]
@alvestrand LMK if I've addressed your question so we can resolve the issue.

**Comment by chcunningham** [comment]
Feel free to re-open if new questions come up
