### ISSUE TITLE
Which interface do I use to get the Screen Color Depth?

### ISSUE THREAD

**Issue by PauKerr** [WICG/media-capabilities#75]
Is this the same property as Screen.colorDepth defined by CSSOM? As written, it looks as if the specification is introducing a property to the Screen object but then never references Screen Color Depth in the following patch description.

**Comment by chcunningham** [comment]
I think this is Duplicate of #74 (just filed a few hours ago). 

This ended up in separate CSS specs. 74 tracks cleanup to remove from MediaCapabilities

**Comment by PauKerr** [comment]
You are correct. This will take care of the dangling definition that I was asking about.
