### ISSUE TITLE
MediaCapabilities returns a type that is not exposed everywhere where the method is expose

### ISSUE THREAD

**Issue by jyavenard** [WICG/media-capabilities#84]
We have:
[Exposed=(Window, Worker)]
interface MediaCapabilities {
  Promise<MediaCapabilitiesInfo> decodingInfo(MediaDecodingConfiguration configuration);
  Promise<MediaCapabilitiesInfo> encodingInfo(MediaEncodingConfiguration configuration);
};

However, MediaCapabilitiesInfo itself isn't exposed anywhere

in https://wicg.github.io/media-capabilities/#idl-index
interface MediaCapabilitiesInfo {
  readonly attribute boolean supported;
  readonly attribute boolean smooth;
  readonly attribute boolean powerEfficient;
};

should be:
[Exposed=(Window, Worker)]
interface MediaCapabilitiesInfo {
  readonly attribute boolean supported;
  readonly attribute boolean smooth;
  readonly attribute boolean powerEfficient;
};

**Comment by chcunningham** [comment]
Yep, seems like we overlooked it. @mounirlamouri - can you double check me (WebIDL noobie)? If you agree I'll submit a fix.

**Comment by mounirlamouri** [comment]
Doing this change seems reasonable. Thanks for spotting the issue @jyavenard

**Comment by jyavenard** [comment]
Please note that there are other issues with the webidl making it not compatible with the current webidl spec. 

It's currently being discussed in https://github.com/heycam/webidl/issues/76

As it is, you can't have optional dictionaries with required members in a dictionary.

I will open another bug once the dust has settled in that bug

**Comment by chcunningham** [comment]
> I will open another bug once the dust has settled in that bug

Thanks, sounds good!
