### ISSUE TITLE
Definition of bitrate should be better defined for VBR

### ISSUE THREAD

**Issue by mwatson2** [WICG/media-capabilities#9]
Video is often encoding with variable bitrate, sometimes highly variable. We need to better describe the meaning of the `bitrate` field of `VideoConfiguration` given this context.

The current definition says that `bitrate` is the _average_ bitrate, but it doesn't clearly specify over what time period the average is calculated. The reference to 'number of bits used to encode a second of video' could be interpreted simply as defining the units (bits-per-second) or as specifying that the video stream described is constant bitrate when averaged over one-second windows.

For example,

> The `bitrate` member specifies an encoded video bitrate in bits-per-second. The capabilities API provides capability information based on an assumption of constant bitrate encoded video. Applications which use variable bitrate encoding should therefore query capabilities based on the peak video encoding rate.

**Comment by chcunningham** [comment]
> Applications which use variable bitrate encoding should therefore query capabilities based on the peak video encoding rate.

What do you think about relaxing the advice here to something like: "should therefore query capabilities based on the bitrate that best characterizes their stream."

I realize thats vague - can definitely be improved. My point is that I could see other content providers being less concerned with how it performs at peak vs how it performs overall. For streams containing some bitrate spikes it might would be undesirable to say "not smooth" if in reality we could smoothly playback 99% of the stream. Still, for folks that want a perfectly flawless smooth playback, using maximum is probably better, so I aim to find some language that gives devs that flexibility.

**Comment by mounirlamouri** [comment]
I think it would be interesting to see how `bandwidth` is being used by HLS and DASH. The primary use case is that `bitrate` (now renamed to `bandwidth`) would be filed based on HLS/DASH data.

**Comment by mwatson2** [comment]
Well, you would need to change the definition as well as the name then. Surely they have to match ?

I'm not sure this is a correct use-case, though. 'bandwidth' in DASH is tailored to that task of specifying the throughout needed to stream the encode. It's not obvious that is the right thing to answer questions about decode capability. It's not obvious we need this field as all, in fact, since we have levels and profiles in the codec string which imply precise bitrate constraints on the encoding.

**Comment by mounirlamouri** [comment]
Are you suggesting that we should drop `bitrate` in favour of levels/profiles? What if there is no level/profile? It sounds to me that developers will know what is the quality of a given video and it's codec but might not be aware of much more. Is that an incorrect assumption?

**Comment by chcunningham** [comment]
I'm in favor of keeping bitrate (and calling it by that name). Mounir is right, not all codecs have a notion of level (e.g. vp8). And even for codecs with level, the buckets can be big and maintaining the logic to turn level into a bitrate is a pain. Having level alongside bitrate is still useful though, especially if you know the decoding will use hardware designed to perform up to a specific level.

**Comment by mounirlamouri** [comment]
I merged a PR from @PauKerr that is adding the clarification. Closing this issue.
