### ISSUE TITLE
MediaCapabilitiesInfo should be a Dictionary

### ISSUE THREAD

**Issue by jernoble** [WICG/media-capabilities#97]
A MediaCapabilitiesInfo is only ever exposed to script through the Promise returned by `decodingInfo()` and `encodingInfo()`.  It has no methods of its own, and can pass it as a parameter to no other function.  It's simply a group of booleans, and so could easily just be a Dictionary.

**Comment by chcunningham** [comment]
We are tentatively planning to add a method to the object to querying for support of transitions between configurations. See [discussion in the explainer](https://github.com/WICG/media-capabilities/blob/master/explainer.md#transitioning-between-stream-configurations).

Also, is it valid to return a dictionary type? I thought we had to return an interface.

**Comment by jernoble** [comment]
@chcunningham 
> We are tentatively planning to add a method to the object to querying for support of transitions between configurations. See discussion in the explainer.

I'm having a difficult time understanding why this API should be on the MediaCapabilitiesInfo itself, and not a separate method on MediaCapabilities; e.g., mediaCapabilities.decodingTransitionInfo(toInfo, fromInfo). Especially because the same object is returned from decodingInfo() and encodingInfo().  The caller would have to track whether the MediaCapabilitiesInfo represented a decode or encode query.

> Also, is it valid to return a dictionary type? I thought we had to return an interface.

I don't think that's a requirement of Web IDL, but I could be wrong. That said, this isn't technically a return value, it's a parameter to a Promise handler.

**Comment by jernoble** [comment]
I've been informed by @eric-carlson that there are lots of examples of dictionaries being returned from methods inside the [Media Capture and Streams API](https://w3c.github.io/mediacapture-main/#media-stream-track-interface-definition), including getCapabilities(), getConstraints(), and getSettings().

**Comment by chcunningham** [comment]
Thanks for those examples. I'm happy to make it a dictionary for now and we can convert to an interface if we end up adding the transition() API later on. For that discussion I've filed #102
